name    'tskirvin-puppet'
version '0.0.1'
source ''
author 'tskirvin'
license 'Apache License, Version 2.0'
summary 'Manage Puppet'
description 'Manages Puppet, including Master, Agent, Dashboard and maintenance tasks.'
project_page ''

dependency 'puppetlabs/stdlib', '3.2.x'
dependency 'puppetlabs/mysql', '>= 0.6.1'
dependency 'puppetlabs/passenger', '>= 0.0.4'
dependency 'puppetlabs/apache', '>= 0.9.0'
dependency 'puppetlabs/firewall', '>= 0.2.1'
